# Generated by Django 3.0.4 on 2020-03-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chondokotha', '0002_auto_20200313_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
