# Generated by Django 3.0.4 on 2020-03-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chondokotha', '0003_auto_20200313_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='lat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='lon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
